[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
k1_yield_vault = "K1VaULt111111111111111111111111111111111111"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p k1-yield-vault"
